//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace DMS.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class JMSEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new JMSEntities object using the connection string found in the 'JMSEntities' section of the application configuration file.
        /// </summary>
        public JMSEntities() : base("name=JMSEntities", "JMSEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new JMSEntities object.
        /// </summary>
        public JMSEntities(string connectionString) : base(connectionString, "JMSEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new JMSEntities object.
        /// </summary>
        public JMSEntities(EntityConnection connection) : base(connection, "JMSEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Attachment> Attachments
        {
            get
            {
                if ((_Attachments == null))
                {
                    _Attachments = base.CreateObjectSet<Attachment>("Attachments");
                }
                return _Attachments;
            }
        }
        private ObjectSet<Attachment> _Attachments;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<History> Histories
        {
            get
            {
                if ((_Histories == null))
                {
                    _Histories = base.CreateObjectSet<History>("Histories");
                }
                return _Histories;
            }
        }
        private ObjectSet<History> _Histories;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Job> Jobs
        {
            get
            {
                if ((_Jobs == null))
                {
                    _Jobs = base.CreateObjectSet<Job>("Jobs");
                }
                return _Jobs;
            }
        }
        private ObjectSet<Job> _Jobs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Note> Notes
        {
            get
            {
                if ((_Notes == null))
                {
                    _Notes = base.CreateObjectSet<Note>("Notes");
                }
                return _Notes;
            }
        }
        private ObjectSet<Note> _Notes;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Attachments EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAttachments(Attachment attachment)
        {
            base.AddObject("Attachments", attachment);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Histories EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToHistories(History history)
        {
            base.AddObject("Histories", history);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Jobs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToJobs(Job job)
        {
            base.AddObject("Jobs", job);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Notes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToNotes(Note note)
        {
            base.AddObject("Notes", note);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="JMSModel", Name="Attachment")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Attachment : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Attachment object.
        /// </summary>
        /// <param name="aPK">Initial value of the APK property.</param>
        /// <param name="jobAPK">Initial value of the JobAPK property.</param>
        /// <param name="attachmentFileName">Initial value of the AttachmentFileName property.</param>
        /// <param name="createdDate">Initial value of the CreatedDate property.</param>
        /// <param name="lastModifyDate">Initial value of the LastModifyDate property.</param>
        public static Attachment CreateAttachment(global::System.Guid aPK, global::System.Guid jobAPK, global::System.String attachmentFileName, global::System.DateTime createdDate, global::System.DateTime lastModifyDate)
        {
            Attachment attachment = new Attachment();
            attachment.APK = aPK;
            attachment.JobAPK = jobAPK;
            attachment.AttachmentFileName = attachmentFileName;
            attachment.CreatedDate = createdDate;
            attachment.LastModifyDate = lastModifyDate;
            return attachment;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid APK
        {
            get
            {
                return _APK;
            }
            set
            {
                if (_APK != value)
                {
                    OnAPKChanging(value);
                    ReportPropertyChanging("APK");
                    _APK = StructuralObject.SetValidValue(value, "APK");
                    ReportPropertyChanged("APK");
                    OnAPKChanged();
                }
            }
        }
        private global::System.Guid _APK;
        partial void OnAPKChanging(global::System.Guid value);
        partial void OnAPKChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid JobAPK
        {
            get
            {
                return _JobAPK;
            }
            set
            {
                OnJobAPKChanging(value);
                ReportPropertyChanging("JobAPK");
                _JobAPK = StructuralObject.SetValidValue(value, "JobAPK");
                ReportPropertyChanged("JobAPK");
                OnJobAPKChanged();
            }
        }
        private global::System.Guid _JobAPK;
        partial void OnJobAPKChanging(global::System.Guid value);
        partial void OnJobAPKChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AttachmentFileName
        {
            get
            {
                return _AttachmentFileName;
            }
            set
            {
                OnAttachmentFileNameChanging(value);
                ReportPropertyChanging("AttachmentFileName");
                _AttachmentFileName = StructuralObject.SetValidValue(value, false, "AttachmentFileName");
                ReportPropertyChanged("AttachmentFileName");
                OnAttachmentFileNameChanged();
            }
        }
        private global::System.String _AttachmentFileName;
        partial void OnAttachmentFileNameChanging(global::System.String value);
        partial void OnAttachmentFileNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AttachmentFileSize
        {
            get
            {
                return _AttachmentFileSize;
            }
            set
            {
                OnAttachmentFileSizeChanging(value);
                ReportPropertyChanging("AttachmentFileSize");
                _AttachmentFileSize = StructuralObject.SetValidValue(value, true, "AttachmentFileSize");
                ReportPropertyChanged("AttachmentFileSize");
                OnAttachmentFileSizeChanged();
            }
        }
        private global::System.String _AttachmentFileSize;
        partial void OnAttachmentFileSizeChanging(global::System.String value);
        partial void OnAttachmentFileSizeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AttachmentFileType
        {
            get
            {
                return _AttachmentFileType;
            }
            set
            {
                OnAttachmentFileTypeChanging(value);
                ReportPropertyChanging("AttachmentFileType");
                _AttachmentFileType = StructuralObject.SetValidValue(value, true, "AttachmentFileType");
                ReportPropertyChanged("AttachmentFileType");
                OnAttachmentFileTypeChanged();
            }
        }
        private global::System.String _AttachmentFileType;
        partial void OnAttachmentFileTypeChanging(global::System.String value);
        partial void OnAttachmentFileTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AttachmentComment
        {
            get
            {
                return _AttachmentComment;
            }
            set
            {
                OnAttachmentCommentChanging(value);
                ReportPropertyChanging("AttachmentComment");
                _AttachmentComment = StructuralObject.SetValidValue(value, true, "AttachmentComment");
                ReportPropertyChanged("AttachmentComment");
                OnAttachmentCommentChanged();
            }
        }
        private global::System.String _AttachmentComment;
        partial void OnAttachmentCommentChanging(global::System.String value);
        partial void OnAttachmentCommentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AttachmentOwner
        {
            get
            {
                return _AttachmentOwner;
            }
            set
            {
                OnAttachmentOwnerChanging(value);
                ReportPropertyChanging("AttachmentOwner");
                _AttachmentOwner = StructuralObject.SetValidValue(value, true, "AttachmentOwner");
                ReportPropertyChanged("AttachmentOwner");
                OnAttachmentOwnerChanged();
            }
        }
        private global::System.String _AttachmentOwner;
        partial void OnAttachmentOwnerChanging(global::System.String value);
        partial void OnAttachmentOwnerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreatedDate
        {
            get
            {
                return _CreatedDate;
            }
            set
            {
                OnCreatedDateChanging(value);
                ReportPropertyChanging("CreatedDate");
                _CreatedDate = StructuralObject.SetValidValue(value, "CreatedDate");
                ReportPropertyChanged("CreatedDate");
                OnCreatedDateChanged();
            }
        }
        private global::System.DateTime _CreatedDate;
        partial void OnCreatedDateChanging(global::System.DateTime value);
        partial void OnCreatedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LastModifyDate
        {
            get
            {
                return _LastModifyDate;
            }
            set
            {
                OnLastModifyDateChanging(value);
                ReportPropertyChanging("LastModifyDate");
                _LastModifyDate = StructuralObject.SetValidValue(value, "LastModifyDate");
                ReportPropertyChanged("LastModifyDate");
                OnLastModifyDateChanged();
            }
        }
        private global::System.DateTime _LastModifyDate;
        partial void OnLastModifyDateChanging(global::System.DateTime value);
        partial void OnLastModifyDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CreatedUserID
        {
            get
            {
                return _CreatedUserID;
            }
            set
            {
                OnCreatedUserIDChanging(value);
                ReportPropertyChanging("CreatedUserID");
                _CreatedUserID = StructuralObject.SetValidValue(value, true, "CreatedUserID");
                ReportPropertyChanged("CreatedUserID");
                OnCreatedUserIDChanged();
            }
        }
        private global::System.String _CreatedUserID;
        partial void OnCreatedUserIDChanging(global::System.String value);
        partial void OnCreatedUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastModifyUserID
        {
            get
            {
                return _LastModifyUserID;
            }
            set
            {
                OnLastModifyUserIDChanging(value);
                ReportPropertyChanging("LastModifyUserID");
                _LastModifyUserID = StructuralObject.SetValidValue(value, true, "LastModifyUserID");
                ReportPropertyChanged("LastModifyUserID");
                OnLastModifyUserIDChanged();
            }
        }
        private global::System.String _LastModifyUserID;
        partial void OnLastModifyUserIDChanging(global::System.String value);
        partial void OnLastModifyUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AttachmentFileExtension
        {
            get
            {
                return _AttachmentFileExtension;
            }
            set
            {
                OnAttachmentFileExtensionChanging(value);
                ReportPropertyChanging("AttachmentFileExtension");
                _AttachmentFileExtension = StructuralObject.SetValidValue(value, true, "AttachmentFileExtension");
                ReportPropertyChanged("AttachmentFileExtension");
                OnAttachmentFileExtensionChanged();
            }
        }
        private global::System.String _AttachmentFileExtension;
        partial void OnAttachmentFileExtensionChanging(global::System.String value);
        partial void OnAttachmentFileExtensionChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="JMSModel", Name="History")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class History : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new History object.
        /// </summary>
        /// <param name="aPK">Initial value of the APK property.</param>
        /// <param name="jobAPK">Initial value of the JobAPK property.</param>
        /// <param name="actionType">Initial value of the ActionType property.</param>
        /// <param name="createdDate">Initial value of the CreatedDate property.</param>
        public static History CreateHistory(global::System.Guid aPK, global::System.Guid jobAPK, global::System.Byte actionType, global::System.DateTime createdDate)
        {
            History history = new History();
            history.APK = aPK;
            history.JobAPK = jobAPK;
            history.ActionType = actionType;
            history.CreatedDate = createdDate;
            return history;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid APK
        {
            get
            {
                return _APK;
            }
            set
            {
                if (_APK != value)
                {
                    OnAPKChanging(value);
                    ReportPropertyChanging("APK");
                    _APK = StructuralObject.SetValidValue(value, "APK");
                    ReportPropertyChanged("APK");
                    OnAPKChanged();
                }
            }
        }
        private global::System.Guid _APK;
        partial void OnAPKChanging(global::System.Guid value);
        partial void OnAPKChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid JobAPK
        {
            get
            {
                return _JobAPK;
            }
            set
            {
                OnJobAPKChanging(value);
                ReportPropertyChanging("JobAPK");
                _JobAPK = StructuralObject.SetValidValue(value, "JobAPK");
                ReportPropertyChanged("JobAPK");
                OnJobAPKChanged();
            }
        }
        private global::System.Guid _JobAPK;
        partial void OnJobAPKChanging(global::System.Guid value);
        partial void OnJobAPKChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte ActionType
        {
            get
            {
                return _ActionType;
            }
            set
            {
                OnActionTypeChanging(value);
                ReportPropertyChanging("ActionType");
                _ActionType = StructuralObject.SetValidValue(value, "ActionType");
                ReportPropertyChanged("ActionType");
                OnActionTypeChanged();
            }
        }
        private global::System.Byte _ActionType;
        partial void OnActionTypeChanging(global::System.Byte value);
        partial void OnActionTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true, "Description");
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreatedDate
        {
            get
            {
                return _CreatedDate;
            }
            set
            {
                OnCreatedDateChanging(value);
                ReportPropertyChanging("CreatedDate");
                _CreatedDate = StructuralObject.SetValidValue(value, "CreatedDate");
                ReportPropertyChanged("CreatedDate");
                OnCreatedDateChanged();
            }
        }
        private global::System.DateTime _CreatedDate;
        partial void OnCreatedDateChanging(global::System.DateTime value);
        partial void OnCreatedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CreatedUserID
        {
            get
            {
                return _CreatedUserID;
            }
            set
            {
                OnCreatedUserIDChanging(value);
                ReportPropertyChanging("CreatedUserID");
                _CreatedUserID = StructuralObject.SetValidValue(value, true, "CreatedUserID");
                ReportPropertyChanged("CreatedUserID");
                OnCreatedUserIDChanged();
            }
        }
        private global::System.String _CreatedUserID;
        partial void OnCreatedUserIDChanging(global::System.String value);
        partial void OnCreatedUserIDChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="JMSModel", Name="Job")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Job : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Job object.
        /// </summary>
        /// <param name="aPK">Initial value of the APK property.</param>
        /// <param name="status">Initial value of the Status property.</param>
        /// <param name="deadline">Initial value of the Deadline property.</param>
        /// <param name="jobID">Initial value of the JobID property.</param>
        /// <param name="jobName">Initial value of the JobName property.</param>
        /// <param name="poster">Initial value of the Poster property.</param>
        /// <param name="createdDate">Initial value of the CreatedDate property.</param>
        /// <param name="lastModifyDate">Initial value of the LastModifyDate property.</param>
        public static Job CreateJob(global::System.Guid aPK, global::System.Byte status, global::System.DateTime deadline, global::System.String jobID, global::System.String jobName, global::System.String poster, global::System.DateTime createdDate, global::System.DateTime lastModifyDate)
        {
            Job job = new Job();
            job.APK = aPK;
            job.Status = status;
            job.Deadline = deadline;
            job.JobID = jobID;
            job.JobName = jobName;
            job.Poster = poster;
            job.CreatedDate = createdDate;
            job.LastModifyDate = lastModifyDate;
            return job;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid APK
        {
            get
            {
                return _APK;
            }
            set
            {
                if (_APK != value)
                {
                    OnAPKChanging(value);
                    ReportPropertyChanging("APK");
                    _APK = StructuralObject.SetValidValue(value, "APK");
                    ReportPropertyChanged("APK");
                    OnAPKChanged();
                }
            }
        }
        private global::System.Guid _APK;
        partial void OnAPKChanging(global::System.Guid value);
        partial void OnAPKChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, "Status");
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.Byte _Status;
        partial void OnStatusChanging(global::System.Byte value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> Priority
        {
            get
            {
                return _Priority;
            }
            set
            {
                OnPriorityChanging(value);
                ReportPropertyChanging("Priority");
                _Priority = StructuralObject.SetValidValue(value, "Priority");
                ReportPropertyChanged("Priority");
                OnPriorityChanged();
            }
        }
        private Nullable<global::System.Byte> _Priority;
        partial void OnPriorityChanging(Nullable<global::System.Byte> value);
        partial void OnPriorityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> Complex
        {
            get
            {
                return _Complex;
            }
            set
            {
                OnComplexChanging(value);
                ReportPropertyChanging("Complex");
                _Complex = StructuralObject.SetValidValue(value, "Complex");
                ReportPropertyChanged("Complex");
                OnComplexChanged();
            }
        }
        private Nullable<global::System.Byte> _Complex;
        partial void OnComplexChanging(Nullable<global::System.Byte> value);
        partial void OnComplexChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> Rate
        {
            get
            {
                return _Rate;
            }
            set
            {
                OnRateChanging(value);
                ReportPropertyChanging("Rate");
                _Rate = StructuralObject.SetValidValue(value, "Rate");
                ReportPropertyChanged("Rate");
                OnRateChanged();
            }
        }
        private Nullable<global::System.Byte> _Rate;
        partial void OnRateChanging(Nullable<global::System.Byte> value);
        partial void OnRateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Deadline
        {
            get
            {
                return _Deadline;
            }
            set
            {
                OnDeadlineChanging(value);
                ReportPropertyChanging("Deadline");
                _Deadline = StructuralObject.SetValidValue(value, "Deadline");
                ReportPropertyChanged("Deadline");
                OnDeadlineChanged();
            }
        }
        private global::System.DateTime _Deadline;
        partial void OnDeadlineChanging(global::System.DateTime value);
        partial void OnDeadlineChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String JobID
        {
            get
            {
                return _JobID;
            }
            set
            {
                OnJobIDChanging(value);
                ReportPropertyChanging("JobID");
                _JobID = StructuralObject.SetValidValue(value, false, "JobID");
                ReportPropertyChanged("JobID");
                OnJobIDChanged();
            }
        }
        private global::System.String _JobID;
        partial void OnJobIDChanging(global::System.String value);
        partial void OnJobIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String JobName
        {
            get
            {
                return _JobName;
            }
            set
            {
                OnJobNameChanging(value);
                ReportPropertyChanging("JobName");
                _JobName = StructuralObject.SetValidValue(value, false, "JobName");
                ReportPropertyChanged("JobName");
                OnJobNameChanged();
            }
        }
        private global::System.String _JobName;
        partial void OnJobNameChanging(global::System.String value);
        partial void OnJobNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Poster
        {
            get
            {
                return _Poster;
            }
            set
            {
                OnPosterChanging(value);
                ReportPropertyChanging("Poster");
                _Poster = StructuralObject.SetValidValue(value, false, "Poster");
                ReportPropertyChanged("Poster");
                OnPosterChanged();
            }
        }
        private global::System.String _Poster;
        partial void OnPosterChanging(global::System.String value);
        partial void OnPosterChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Recipient
        {
            get
            {
                return _Recipient;
            }
            set
            {
                OnRecipientChanging(value);
                ReportPropertyChanging("Recipient");
                _Recipient = StructuralObject.SetValidValue(value, true, "Recipient");
                ReportPropertyChanged("Recipient");
                OnRecipientChanged();
            }
        }
        private global::System.String _Recipient;
        partial void OnRecipientChanging(global::System.String value);
        partial void OnRecipientChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Confirmer
        {
            get
            {
                return _Confirmer;
            }
            set
            {
                OnConfirmerChanging(value);
                ReportPropertyChanging("Confirmer");
                _Confirmer = StructuralObject.SetValidValue(value, true, "Confirmer");
                ReportPropertyChanged("Confirmer");
                OnConfirmerChanged();
            }
        }
        private global::System.String _Confirmer;
        partial void OnConfirmerChanging(global::System.String value);
        partial void OnConfirmerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Note
        {
            get
            {
                return _Note;
            }
            set
            {
                OnNoteChanging(value);
                ReportPropertyChanging("Note");
                _Note = StructuralObject.SetValidValue(value, true, "Note");
                ReportPropertyChanged("Note");
                OnNoteChanged();
            }
        }
        private global::System.String _Note;
        partial void OnNoteChanging(global::System.String value);
        partial void OnNoteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DepartmentID
        {
            get
            {
                return _DepartmentID;
            }
            set
            {
                OnDepartmentIDChanging(value);
                ReportPropertyChanging("DepartmentID");
                _DepartmentID = StructuralObject.SetValidValue(value, true, "DepartmentID");
                ReportPropertyChanged("DepartmentID");
                OnDepartmentIDChanged();
            }
        }
        private global::System.String _DepartmentID;
        partial void OnDepartmentIDChanging(global::System.String value);
        partial void OnDepartmentIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreatedDate
        {
            get
            {
                return _CreatedDate;
            }
            set
            {
                OnCreatedDateChanging(value);
                ReportPropertyChanging("CreatedDate");
                _CreatedDate = StructuralObject.SetValidValue(value, "CreatedDate");
                ReportPropertyChanged("CreatedDate");
                OnCreatedDateChanged();
            }
        }
        private global::System.DateTime _CreatedDate;
        partial void OnCreatedDateChanging(global::System.DateTime value);
        partial void OnCreatedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LastModifyDate
        {
            get
            {
                return _LastModifyDate;
            }
            set
            {
                OnLastModifyDateChanging(value);
                ReportPropertyChanging("LastModifyDate");
                _LastModifyDate = StructuralObject.SetValidValue(value, "LastModifyDate");
                ReportPropertyChanged("LastModifyDate");
                OnLastModifyDateChanged();
            }
        }
        private global::System.DateTime _LastModifyDate;
        partial void OnLastModifyDateChanging(global::System.DateTime value);
        partial void OnLastModifyDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CreatedUserID
        {
            get
            {
                return _CreatedUserID;
            }
            set
            {
                OnCreatedUserIDChanging(value);
                ReportPropertyChanging("CreatedUserID");
                _CreatedUserID = StructuralObject.SetValidValue(value, true, "CreatedUserID");
                ReportPropertyChanged("CreatedUserID");
                OnCreatedUserIDChanged();
            }
        }
        private global::System.String _CreatedUserID;
        partial void OnCreatedUserIDChanging(global::System.String value);
        partial void OnCreatedUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastModifyUserID
        {
            get
            {
                return _LastModifyUserID;
            }
            set
            {
                OnLastModifyUserIDChanging(value);
                ReportPropertyChanging("LastModifyUserID");
                _LastModifyUserID = StructuralObject.SetValidValue(value, true, "LastModifyUserID");
                ReportPropertyChanged("LastModifyUserID");
                OnLastModifyUserIDChanged();
            }
        }
        private global::System.String _LastModifyUserID;
        partial void OnLastModifyUserIDChanging(global::System.String value);
        partial void OnLastModifyUserIDChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="JMSModel", Name="Note")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Note : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Note object.
        /// </summary>
        /// <param name="aPK">Initial value of the APK property.</param>
        /// <param name="jobAPK">Initial value of the JobAPK property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        /// <param name="createdDate">Initial value of the CreatedDate property.</param>
        /// <param name="lastModifyDate">Initial value of the LastModifyDate property.</param>
        public static Note CreateNote(global::System.Guid aPK, global::System.Guid jobAPK, global::System.String description, global::System.DateTime createdDate, global::System.DateTime lastModifyDate)
        {
            Note note = new Note();
            note.APK = aPK;
            note.JobAPK = jobAPK;
            note.Description = description;
            note.CreatedDate = createdDate;
            note.LastModifyDate = lastModifyDate;
            return note;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid APK
        {
            get
            {
                return _APK;
            }
            set
            {
                if (_APK != value)
                {
                    OnAPKChanging(value);
                    ReportPropertyChanging("APK");
                    _APK = StructuralObject.SetValidValue(value, "APK");
                    ReportPropertyChanged("APK");
                    OnAPKChanged();
                }
            }
        }
        private global::System.Guid _APK;
        partial void OnAPKChanging(global::System.Guid value);
        partial void OnAPKChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid JobAPK
        {
            get
            {
                return _JobAPK;
            }
            set
            {
                OnJobAPKChanging(value);
                ReportPropertyChanging("JobAPK");
                _JobAPK = StructuralObject.SetValidValue(value, "JobAPK");
                ReportPropertyChanged("JobAPK");
                OnJobAPKChanged();
            }
        }
        private global::System.Guid _JobAPK;
        partial void OnJobAPKChanging(global::System.Guid value);
        partial void OnJobAPKChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false, "Description");
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreatedDate
        {
            get
            {
                return _CreatedDate;
            }
            set
            {
                OnCreatedDateChanging(value);
                ReportPropertyChanging("CreatedDate");
                _CreatedDate = StructuralObject.SetValidValue(value, "CreatedDate");
                ReportPropertyChanged("CreatedDate");
                OnCreatedDateChanged();
            }
        }
        private global::System.DateTime _CreatedDate;
        partial void OnCreatedDateChanging(global::System.DateTime value);
        partial void OnCreatedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LastModifyDate
        {
            get
            {
                return _LastModifyDate;
            }
            set
            {
                OnLastModifyDateChanging(value);
                ReportPropertyChanging("LastModifyDate");
                _LastModifyDate = StructuralObject.SetValidValue(value, "LastModifyDate");
                ReportPropertyChanged("LastModifyDate");
                OnLastModifyDateChanged();
            }
        }
        private global::System.DateTime _LastModifyDate;
        partial void OnLastModifyDateChanging(global::System.DateTime value);
        partial void OnLastModifyDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CreatedUserID
        {
            get
            {
                return _CreatedUserID;
            }
            set
            {
                OnCreatedUserIDChanging(value);
                ReportPropertyChanging("CreatedUserID");
                _CreatedUserID = StructuralObject.SetValidValue(value, true, "CreatedUserID");
                ReportPropertyChanged("CreatedUserID");
                OnCreatedUserIDChanged();
            }
        }
        private global::System.String _CreatedUserID;
        partial void OnCreatedUserIDChanging(global::System.String value);
        partial void OnCreatedUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastModifyUserID
        {
            get
            {
                return _LastModifyUserID;
            }
            set
            {
                OnLastModifyUserIDChanging(value);
                ReportPropertyChanging("LastModifyUserID");
                _LastModifyUserID = StructuralObject.SetValidValue(value, true, "LastModifyUserID");
                ReportPropertyChanged("LastModifyUserID");
                OnLastModifyUserIDChanged();
            }
        }
        private global::System.String _LastModifyUserID;
        partial void OnLastModifyUserIDChanging(global::System.String value);
        partial void OnLastModifyUserIDChanged();

        #endregion

    }

    #endregion

}
