IF NOT EXISTS (SELECT TOP 1 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[Notes]') AND TYPE IN (N'U'))
BEGIN
     CREATE TABLE [dbo].[Notes]
     (
		[APK] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
		[JobAPK] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
		[Description] NVARCHAR(MAX) NOT NULL,
		[CreatedDate] DATETIME NOT NULL DEFAULT GETDATE(),
		[LastModifyDate] DATETIME NOT NULL DEFAULT GETDATE(),
		[CreatedUserID] NVARCHAR(50) NULL,
		[LastModifyUserID] NVARCHAR(50) NULL,
		CONSTRAINT [PK_NOTES_APK] PRIMARY KEY CLUSTERED
		(
			[APK]
		)
		WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	)
	ON [PRIMARY]
END